[package]
name = "math"
version = "0.1.0"
edition = "2024"

[dependencies]
boiler = { git = "https://github.com/snqre/boiler.git" }
syn = { version = "2.0.100", features = ["full"]}
quote = "1.0"

[dependencies.num-traits]
version = "=0.2.19"
[dependencies.thiserror]
version = "=2.0.12"

[dependencies.automod]
version = "*"