boiler::bundle!("src/obj_q");
boiler::expose!(
    enu_error,
    ext_add,
    ext_branded,
    ext_cap_introspection,
    ext_cast,
    ext_constructor_int,
    ext_constructor,
    ext_div,
    ext_eq,
    ext_log,
    ext_mul,
    ext_muldiv,
    ext_ord,
    ext_partial_eq,
    ext_partial_ord,
    ext_prime_introspection,
    ext_rem,
    ext_sign_introspection,
    ext_sqrt,
    ext_sub,
    ext_to_f32,
    ext_to_f64,
    ext_to_i8,
    ext_to_i16,
    ext_to_i32,
    ext_to_i64,
    ext_to_i128,
    ext_to_isize,
    ext_to_u8,
    ext_to_u16,
    ext_to_u32,
    ext_to_u64,
    ext_to_u128,
    ext_to_usize,
    ext_trig_reciprocal,
    ext_trig,
    ext_trunc,
    ext_try_from_i8,
    ext_try_from_i16,
    ext_try_from_i32,
    ext_try_from_i64,
    ext_try_from_i128,
    ext_try_from_isize,
    ext_try_from_u8,
    ext_try_from_u16,
    ext_try_from_u32,
    ext_try_from_u64,
    ext_try_from_u128,
    ext_try_from_usize,
    obj_check_precision,
    t_result,
    tr_branded_for_i8,
    tr_branded_for_i16,
    tr_branded_for_i32,
    tr_branded_for_i64,
    tr_branded_for_i128,
    tr_branded_for_isize,
    tr_branded_for_u8,
    tr_branded_for_u16,
    tr_branded_for_u32,
    tr_branded_for_u64,
    tr_branded_for_u128,
    tr_branded_for_usize,
    tr_branded,
    tr_is_precision_for_obj_check_precision_1u8,
    tr_is_precision_for_obj_check_precision_2u8,
    tr_is_precision_for_obj_check_precision_3u8,
    tr_is_precision_for_obj_check_precision_4u8,
    tr_is_precision_for_obj_check_precision_5u8,
    tr_is_precision_for_obj_check_precision_6u8,
    tr_is_precision,
    tr_sign_introspection_for_i8,
    tr_sign_introspection_for_i16,
    tr_sign_introspection_for_i32,
    tr_sign_introspection_for_i64,
    tr_sign_introspection_for_i128,
    tr_sign_introspection_for_isize,
    tr_sign_introspection_for_u8,
    tr_sign_introspection_for_u16,
    tr_sign_introspection_for_u32,
    tr_sign_introspection_for_u64,
    tr_sign_introspection_for_u128,
    tr_sign_introspection_for_usize,
    tr_sign_introspection,
);

use core::ops::Add;
use core::ops::Sub;
use core::ops::Mul;
use core::ops::Div;
use core::ops::Rem;
use core::cmp::Ordering;
use num_traits::int::PrimInt;
use thiserror::Error;

#[derive(Debug)]
#[derive(Clone)]
#[derive(Copy)]
pub struct Q<const A: u8, B: PrimInt> where _CheckPrecision<A>: _IsPrecision {
    pub(super) _v: B,
}